Repository traas-stack/chaosmeta, pull requests merged in 2023-10, with the labels that each got.

#88 fix: Optimize implementation logic for mem and network fault; mem fault relay "/bin/bash"
  chaosmetad/build/ci/build.sh
  chaosmetad/pkg/crclient/containerd/client.go
  chaosmetad/pkg/exec/mem/chaosmeta_mem.go
  chaosmetad/pkg/exec/network/chaosmeta_network.go
  chaosmetad/pkg/injector/mem/fill.go
  chaosmetad/pkg/injector/network/constant.go
  chaosmetad/pkg/injector/network/corrupt.go
  chaosmetad/pkg/injector/network/delay.go
  chaosmetad/pkg/injector/network/duplicate.go
  chaosmetad/pkg/injector/network/limit.go
  chaosmetad/pkg/injector/network/loss.go
  chaosmetad/pkg/injector/network/occupy.go
  chaosmetad/pkg/injector/network/reorder.go
  chaosmetad/pkg/utils/cmdexec/cmd.go
  chaosmetad/pkg/utils/net/net.go
  chaosmetad/tools/chaosmeta_memfill.go
Labels: bug

#89 fix: optimize oom fault
  chaosmetad/pkg/injector/mem/constant.go
  chaosmetad/pkg/injector/mem/oom.go
Labels: bug

#90 fix: fix rely on '/bin/bash' in container exec
  chaosmetad/build/ci/build.sh
  chaosmetad/pkg/exec/execns/chaosmeta_execns.c
  chaosmetad/pkg/injector/dns/record.go
  chaosmetad/pkg/injector/dns/server.go
  chaosmetad/pkg/injector/jvm/constant.go
  chaosmetad/pkg/injector/jvm/methoddelay.go
  chaosmetad/pkg/injector/jvm/methodexception.go
  chaosmetad/pkg/injector/jvm/methodreturn.go
  chaosmetad/pkg/injector/mem/fill.go
  chaosmetad/pkg/injector/mem/oom.go
  chaosmetad/pkg/injector/network/occupy.go
  chaosmetad/pkg/utils/cmdexec/cmd.go
  chaosmetad/pkg/utils/errutil/error.go
  chaosmetad/pkg/utils/filesys/filesystem.go
  chaosmetad/pkg/utils/process/process.go
  chaosmetad/test/main.go
  chaosmetad/test/testcase/file/fileadd.go
  chaosmetad/test/testcase/file/filechmod.go
  chaosmetad/test/testcase/mem/memfill.go
  chaosmetad/tools/common/common.go
Labels: bug

#91 fix: mem percent calculate; awk in container
  chaosmetad/build/ci/build.sh
  chaosmetad/pkg/injector/mem/fill.go
  chaosmetad/pkg/injector/mem/oom.go
  chaosmetad/pkg/utils/memory/mem.go
  chaosmetad/pkg/utils/net/net.go
  chaosmetad/pkg/utils/process/process.go
  chaosmetad/tools/chaosmeta_memfill.go
Labels: bug

#92 feat: Supports appending files in a loop
  chaosmetad/build/ci/build.sh
  chaosmetad/pkg/injector/file/append.go
  chaosmetad/pkg/utils/filesys/filesystem.go
  chaosmetad/pkg/utils/process/process.go
Labels: enhancement

#95 fix: error occurred while injecting memory failure into a container u…
  chaosmetad/pkg/utils/cgroup/type.go
  chaosmetad/pkg/utils/common.go
  chaosmetad/pkg/utils/memory/mem.go
Labels: bug, enhancement

#99 Fixed experiment result node display
  chaosmeta-platform-frontend/src/pages/Space/ExperimentDetail/ArrangeInfoShow.tsx
Labels: bug

#100 fix: mem fault not rely on /proc/meminfo, change to rely to /sys/fs/cgroup/memory
  chaosmeta-deploy/templates/chaosmeta-daemon-template.yaml
  chaosmeta-deploy/templates/chaosmeta-inject-template.yaml
  chaosmeta-inject-operator/build/yamls/chaosmeta-daemonset.yaml
  chaosmeta-inject-operator/config/chaosmeta-inject.json
  chaosmetad/build/chaosmeta-daemonset.Dockerfile
  chaosmetad/build/chaosmetad-demo.Dockerfile
  chaosmetad/build/ci/build.sh
  chaosmetad/pkg/injector/cpu/burn_linux.go
  chaosmetad/pkg/utils/cgroup/cgroup_linux.go
  chaosmetad/pkg/utils/cgroup/type.go
  chaosmetad/pkg/utils/common.go
  chaosmetad/pkg/utils/memory/mem.go
  chaosmetad/test/main.go
Labels: bug, enhancement

#103 feat: support reload images to registry
  chaosmeta-deploy/deploy.sh
  chaosmeta-deploy/retag_image.sh
  chaosmeta-deploy/templates/chaosmeta-daemon-template.yaml
  chaosmeta-deploy/templates/chaosmeta-flow-template.yaml
  chaosmeta-deploy/templates/chaosmeta-inject-template.yaml
  chaosmeta-deploy/templates/chaosmeta-measure-template.yaml
  chaosmeta-deploy/templates/chaosmeta-platform-template.yaml
  chaosmeta-deploy/templates/chaosmeta-workflow-template.yaml
Labels: enhancement

#104 fix: deploy tip error
  chaosmeta-deploy/deploy.sh
Labels: bug

#107 fix: readme start up
  README.md
  README_CN.md
Labels: documentation
