Repository traas-stack/chaosmeta, pull requests merged in 2023-09, with the labels that each got.

#63 fix: update readme add English version
  README.md
  README_CN.md
  README_backup.md
  docs/static/riskdir_en.png
Labels: documentation

#64 docs: fix English url
  README.md
Labels: documentation

#65 docs: update README url
  README.md
Labels: documentation

#66 V0.2.1
  README.md
  README_CN.md
Labels: documentation

#67 feature: chaosmetad support containerd
  chaosmeta-deploy/deploy.sh
  chaosmeta-deploy/templates/chaosmeta-daemon-template.yaml
  chaosmeta-deploy/templates/chaosmeta-inject-template.yaml
  chaosmeta-inject-operator/config/chaosmeta-inject.json
  chaosmeta-platform/go.sum
  chaosmetad/build/chaosmeta-daemonset.Dockerfile
  chaosmetad/build/chaosmetad-demo.Dockerfile
  chaosmetad/build/ci/build.sh
  chaosmetad/go.mod
  chaosmetad/go.sum
  chaosmetad/pkg/crclient/client.go
  chaosmetad/pkg/crclient/containerd/client.go
  chaosmetad/pkg/crclient/docker/client.go
  chaosmetad/pkg/crclient/pouch/client.go
  chaosmetad/pkg/utils/filesys/filesystem.go
Labels: enhancement

#79 Fixes #73 Use the '=' instead of the space symbol to combine the network inject…
  chaosmeta-inject-operator/pkg/executor/remoteexecutor/daemonsetexecutor/daemonsetexecutor.go
Labels: bug

#80 feature: Support JVM fault to container; fix: add app label to operator deployment/service;fix: Merge the execution tools of the process and the file module
  chaosmeta-deploy/templates/chaosmeta-daemon-template.yaml
  chaosmeta-deploy/templates/chaosmeta-flow-template.yaml
  chaosmeta-deploy/templates/chaosmeta-inject-template.yaml
  chaosmeta-deploy/templates/chaosmeta-measure-template.yaml
  chaosmeta-deploy/tools/build.sh
  chaosmeta-flow-operator/config/manager/manager.yaml
  chaosmeta-flow-operator/config/webhook/service.yaml
  chaosmeta-inject-operator/config/chaosmeta-inject.json
  chaosmeta-inject-operator/config/manager/manager.yaml
  chaosmeta-inject-operator/config/webhook/service.yaml
  chaosmeta-measure-operator/config/manager/manager.yaml
  chaosmeta-measure-operator/config/webhook/service.yaml
  chaosmetad/build/chaosmeta-daemonset.Dockerfile
  chaosmetad/build/chaosmetad-demo.Dockerfile
  chaosmetad/build/ci/build.sh
  chaosmetad/pkg/crclient/containerd/client.go
  chaosmetad/pkg/crclient/docker/client.go
  chaosmetad/pkg/crclient/pouch/client.go
  chaosmetad/pkg/exec/disk/chaosmeta_diskfill.go
  chaosmetad/pkg/exec/diskio/chaosmeta_diskio.go
  chaosmetad/pkg/exec/file/chaosmeta_file.go
  chaosmetad/pkg/exec/mem/chaosmeta_mem.go
  chaosmetad/pkg/exec/process/chaosmeta_process.go
  chaosmetad/pkg/injector/disk/fill.go
  chaosmetad/pkg/injector/diskio/hang_linux.go
  chaosmetad/pkg/injector/diskio/limit_linux.go
  chaosmetad/pkg/injector/file/add.go
  chaosmetad/pkg/injector/file/append.go
  chaosmetad/pkg/injector/file/chmod.go
  chaosmetad/pkg/injector/file/constant.go
  chaosmetad/pkg/injector/file/delete.go
  chaosmetad/pkg/injector/file/mv.go
  chaosmetad/pkg/injector/jvm/constant.go
  chaosmetad/pkg/injector/jvm/methoddelay.go
  chaosmetad/pkg/injector/jvm/methodexception.go
  chaosmetad/pkg/injector/jvm/methodreturn.go
  chaosmetad/pkg/injector/kernel/fdfull.go
  chaosmetad/pkg/injector/network/occupy.go
  chaosmetad/pkg/injector/process/constant.go
  chaosmetad/pkg/injector/process/kill.go
  chaosmetad/pkg/injector/process/stop.go
  chaosmetad/pkg/utils/cmdexec/cmd.go
  chaosmetad/pkg/utils/errutil/error.go
  chaosmetad/pkg/utils/filesys/filesystem.go
  chaosmetad/pkg/utils/process/process.go
  chaosmetad/test/main.go
  chaosmetad/test/testcase/disk/diskfill.go
  chaosmetad/test/testcase/diskio/diskioburn.go
  chaosmetad/test/testcase/file/fileadd.go
  chaosmetad/test/testcase/file/fileappend.go
  chaosmetad/test/testcase/file/filechmod.go
  chaosmetad/test/testcase/file/filedelete.go
  chaosmetad/test/testcase/file/filemv.go
  chaosmetad/test/testcase/mem/memfill.go
Labels: bug, enhancement
